### ISSUE TITLE
Add button to pick selfie from library

### ISSUE THREAD

**Issue by Maxime-Oriol** [Greenstand/treetracker-ios#24] opened 2020-09-10 15:23 UTC
As a user, I want to select selfie picture from library

**Acceptance Criteria**
When I sign up, on the Selfie screen, can I see a button to select picture from library
When I select a picture from library, does the picture is saved in my profile

Out of Scope
The app doesn't crash when executed on simulator

**Comment by AlexCornforth** [comment] 2020-09-10 16:37
Hi @Maxime-Oriol 👋 

Great that you want to help out!

The absence of the photo library button is by design. We use the planters selfie photo to verify who is planting the trees therefore the photo needs to be taken of the planter at the time of sign in. 

We have plenty to work on though. If you are interested in helping out please follow the process on our [volunteer page](https://greenstand.org/contribute) and join the slack workspace.

**Comment by AlexCornforth** [comment] 2020-09-10 16:38
Closing this issue as the absence of the photo library button is by design.

**Closed as completed by AlexCornforth** 2020-09-10 16:38 UTC
